# Generated by Django 6.0.3 on 2026-03-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#3498db', 'Blue'), ('#e74c3c', 'Red'), ('#2ecc71', 'Green')], default='#3498db', help_text='Color in hex format (e.g., #3498db)', max_length=7),
        ),
    ]
