# Generated by Django 6.0.3 on 2026-04-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_appointment_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='title',
        ),
    ]
